version: "3"

volumes:
  nextcloud-data:
  nextcloud_apache_data:
  nextcloud-db:
  # npm-data:
  # npm-ssl:
  # npm-db:

networks:
  frontend:
  backend:

services:
  nextcloud-app:
    container_name: nextcloud
    build: 
      context: dockerfile
      dockerfile: nextcloud.dockerfile
    restart: always
    volumes:
      - nextcloud-data:/var/www/html

    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
      - PHP_UPLOAD_LIMIT=50G
      - TRUSTED_DOMAINS=[]

    networks:
      - frontend
      - backend
    depends_on:
      - nextcloud-db
      - npm-app
      - redis

  nextcloud-db:
    image: mariadb:11.4
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  # npm-app:
  #   image: jc21/nginx-proxy-manager:latest
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #     - "443:443"
  #   environment:
  #     - DB_MYSQL_HOST=npm-db
  #     - DB_MYSQL_PORT=3306
  #     - DB_MYSQL_USER=npm
  #     - DB_MYSQL_PASSWORD=nextcloud
  #     - DB_MYSQL_NAME=npm
  #   volumes:
  #     - npm-data:/data
  #     - npm-ssl:/etc/letsencrypt
  #   networks:
  #     - frontend
  #     - backend  
  
  # npm-db:
  #   image: jc21/mariadb-aria:latest
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=nextcloud
  #     - MYSQL_DATABASE=npm
  #     - MYSQL_USER=npm
  #     - MYSQL_PASSWORD=nextcloud
  #   volumes:
  #     - npm-db:/var/lib/mysql
  #   networks:
  #     - backend

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend
